### ISSUE TITLE
Broadcast Spend transactions

### ISSUE THREAD

**Issue by darosior** [revault/coordinatord#40]
Currently we assume the managers to always have their wallet up by the time the Unvault timelock expires and they can broadcast their Spend tx. That's not a reasonable expectation in most usecases and it could be "easily" fixed by requiring the Coordinator to also have a `bitcoind` and to broadcast the transaction.

**Comment by darosior** [comment]
Somewhat related to https://github.com/revault/practical-revault/issues/102

**Comment by darosior** [comment]
This can be tested using `revaultd`'s test suite, post integration there.

**Comment by danielabrozzoni** [comment]
Closed by #46
