### ISSUE TITLE
Allow coordinatord to be run on non-linux systems

### ISSUE THREAD

**Issue by danielabrozzoni** [revault/coordinatord#41]
https://github.com/revault/coordinatord/blob/master/src/bin/coordinatord.rs#L224:L229 explicitly kills the coordinatord if it's compiled for non-linux systems, which means that aquarium can't be tried out on a Mac. 
After removing the explicit check coordinatord would run and work correctly on my Mac (OS version 10.14).
Maybe we should relax the condition a bit, and allow coordinatord to be run on every unix system? We obviously won't run the coordinatord server on a Mac in production, but it would be really useful for testing or aquarium.

@darosior thoughts?

**Comment by darosior** [comment]
Ack.
‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
