### ISSUE TITLE
Spurious failure to store signatures in `revocationtxs`

### ISSUE THREAD

**Issue by darosior** [revault/coordinatord#45]
See https://github.com/revault/revaultd/issues/356.
It was very likely introduced in https://github.com/revault/coordinatord/pull/43.

**Comment by darosior** [comment]
I think it happens on `revaultd` since https://github.com/revault/revaultd/pull/341. So maybe it has something to do there as well.

**Comment by danielabrozzoni** [comment]
Closed by https://github.com/revault/coordinatord/pull/47

**Comment by darosior** [comment]
It happened again, but not for the same reason apparently. I think #50 finally fixes this.
